AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Globals:
  Api:
    OpenApiVersion: 3.0.1
Parameters:
  Stage:
    Type: String
    Default: staging
  ServiceName:
    Type: String
    Default: s3Consumer
  ArtifactStore:
    Description: S3 Bucket, which will hold the artifacts and open api specs
    Type: String
    Default: uchenchostorage
Resources:
  S3ConsumerBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: s3-consumer-bucket-${Stage}
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName:
        Ref: Stage
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location:
              Fn::Sub: s3://${ArtifactStore}/open-api/${ServiceName}/open-api-integrated.yaml
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Timeout: 180
      MemorySize: 512
      Runtime: go1.x
      FunctionName:
        Fn::Sub: ${ServiceName}-${Stage}
      Environment:
        Variables:
          S3_BUCKET:
            Ref: S3ConsumerBucket
      Policies:
      - VPCAccessPolicy: {}
      - S3CrudPolicy:
          BucketName:
            Ref: S3ConsumerBucket
      Events:
        Register:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Path: /upload
            Method: post
      CodeUri: s3://uchenchostorage/01b50d4311c059bf9b90d627d701a82b
Outputs:
  Endpoint:
    Description: Api endpoint for GeraldAccount
    Value:
      Fn::Sub: https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/
    Export:
      Name:
        Fn::Sub: ${ServiceName}-endpoint
  FunctionName:
    Description: Service Function Name
    Value:
      Fn::Sub: ${ServiceName}-${Stage}
    Export:
      Name:
        Fn::Sub: ${ServiceName}-name
  FunctionArn:
    Description: Service Function ARN
    Value:
      Fn::GetAtt:
      - Function
      - Arn
    Export:
      Name:
        Fn::Sub: ${ServiceName}-arn
