---
AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Globals:
  Api:
    OpenApiVersion: 3.0.1

Parameters:
  Stage:
    Type: String
    Default: staging

  ServiceName:
    Type: String
    Default: s3Consumer

  ArtifactStore:
    Description: S3 Bucket, which will hold the artifacts and open api specs
    Type: String
    Default: uchenchostorage


Resources:

  S3ConsumerBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub s3-consumer-bucket-${Stage}

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      DefinitionBody:
        "Fn::Transform":
          Name: AWS::Include
          Parameters:
            Location: !Sub s3://${ArtifactStore}/open-api/${ServiceName}/open-api-integrated.yaml

  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Timeout: 180
      MemorySize: 512
      Runtime: go1.x
      FunctionName: !Sub ${ServiceName}-${Stage}
      Environment:
        Variables:
          S3_BUCKET: !Ref S3ConsumerBucket
      Policies:
        - VPCAccessPolicy: {}
      Events:
        Register:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /upload
            Method: post


Outputs:
  Endpoint:
    Description: Api endpoint for GeraldAccount
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/
    Export:
      Name: !Sub ${ServiceName}-endpoint
  
  FunctionName:
    Description: Service Function Name
    Value: !Sub ${ServiceName}-${Stage}
    Export:
      Name: !Sub ${ServiceName}-name

  FunctionArn:
    Description: Service Function ARN
    Value: !GetAtt Function.Arn
    Export:
      Name: !Sub ${ServiceName}-arn
  